# Generated by Django 4.2 on 2023-04-24 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('licence_plate', models.CharField(max_length=50, verbose_name='Licence plate')),
                ('vin_code', models.CharField(max_length=24, verbose_name='VIN code')),
                ('client', models.CharField(help_text='Enter client:', max_length=100, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, verbose_name='Car brand')),
                ('car_model', models.CharField(max_length=50, verbose_name='Car model')),
                ('year', models.DateField(verbose_name='Car year')),
                ('engine', models.CharField(max_length=20, verbose_name='Car engine')),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2023, 4, 24), verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.car')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter service name:', max_length=100, verbose_name='Service name')),
                ('price', models.IntegerField(help_text='Enter service price:', verbose_name='Service price ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderRow',
            fields=[
                ('order_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.order')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.service')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.carmodel'),
        ),
    ]
