# Generated by Django 4.2 on 2023-04-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.carmodel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.car'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.order'),
        ),
    ]
