# Generated by Django 4.2 on 2023-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_alter_orderrow_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrow',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderrow',
            old_name='service_id',
            new_name='service',
        ),
    ]
