# Generated by Django 4.2 on 2023-04-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_rename_order_id_orderrow_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrow',
            name='service',
        ),
        migrations.AddField(
            model_name='orderrow',
            name='service',
            field=models.ManyToManyField(to='car_app.service'),
        ),
    ]
