# Generated by Django 4.2 on 2023-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0007_remove_orderrow_service_orderrow_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model_id',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car_id',
            new_name='car',
        ),
        migrations.AddField(
            model_name='orderrow',
            name='cars',
            field=models.ManyToManyField(to='car_app.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(max_length=17, verbose_name='VIN code'),
        ),
    ]
