# Generated by Django 4.2 on 2023-04-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_rename_car_model_id_car_car_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrow',
            name='service',
        ),
        migrations.AddField(
            model_name='orderrow',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.service'),
        ),
    ]
