# Generated by Django 4.2 on 2023-04-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0009_remove_orderrow_service_orderrow_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('order_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('service_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('cars', models.ManyToManyField(to='car_app.carmodel')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.service')),
            ],
            options={
                'ordering': ['service_price_id'],
            },
        ),
        migrations.DeleteModel(
            name='OrderRow',
        ),
    ]
