# Generated by Django 4.2 on 2023-04-26 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0010_orderlist_serviceprice_delete_orderrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
